service: clambda-av

params:
  default:
    scanbucket: "pg-clamav-test"
    
provider:
  name: aws
  runtime: nodejs14.x
  versionFunctions: false
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:GetObject
        - s3:PutObjectTagging
      Resource: arn:aws:s3:::${param:scanbucket}/*

functions:
  virusScan:
    handler: handler.virusScan
    memorySize: 2048
    events:
      - s3: 
          bucket: ${param:scanbucket}
          event: s3:ObjectCreated:*
    layers:
      - {Ref: ClamavLambdaLayer}
    timeout: 120

package:
  exclude:
    - node_modules/**
    - coverage/**

layers:
  clamav:
    path: layer

plugins:
  - serverless-prune-plugin
  - serverless-plugin-include-dependencies

custom:
  prune:
    automatic: true
    number: 1
