#!/bin/bash
which jq &> /dev/null ||exit 1
which yq &> /dev/null ||exit 1

REGION=us-east-1
DEPLOYENV=dev
BUCKET=$(cat serverless.yml| yq '.params.default.scanbucket')
ACCOUNT=$(aws sts get-caller-identity | jq -r ".Account")
SERVICE=$(cat serverless.yml| yq '.service')
TMPFILE=temp.yml
set -x
cat policies/bucket-lifecycle-configuration.yml > ${TMPFILE}
aws s3api put-bucket-lifecycle-configuration --bucket ${BUCKET} --lifecycle-configuration file://${TMPFILE}
cat policies/bucket-policy.yml \
	| sed -e "s/__BUCKET__/${BUCKET}/g" \
	| sed -e "s/__REGION__/${REGION}/g" \
	| sed -e "s/__ACCOUNT__/${ACCOUNT}/g" \
        | sed -e "s/__SERVICE__/${SERVICE}/g" \
        | sed -e "s/__DEPLOYENV__/${DEPLOYENV}/g" \
	> ${TMPFILE}
aws s3api put-bucket-policy --bucket ${BUCKET} --policy file://${TMPFILE}
set -
rm ${TMPFILE}
